version: 0.2

env:
  variables:
    AWS_REGION: 'us-east-2'
    ACCOUNT_ID: '023196572641'
    ECR_REPO: "023196572641.dkr.ecr.us-east-2.amazonaws.com/ronn4/app-repo"
    IMAGE_TAG: "${CODEBUILD_BUILD_ID}"
    APP_IMAGE: "${ECR_REPO}:app-${IMAGE_TAG}"
    DOCKER_REPO: 'ronn4/repo1'
    NAMESPACE: 'ronn4-jenkins'
    APP_IMAGE_NAME: 'app-image-latest'

phases:
  install:
    commands:
      - echo "Installing Python dependencies..."
      - mkdir -p build/venv
      - python3 -m venv build/venv
      - . build/venv/bin/activate
      - pip install pytest unittest2 pylint flask telebot Pillow loguru matplotlib
    finally:
      - echo "Completed installation phase."

  pre_build:
    commands:
      - echo "Checking out code..."
      - git --version
      - mkdir -p repo && cd repo
      - git clone https://github.com/ronnirz4/AWS.git .
      - git rev-parse --short HEAD > gitCommit.txt
      - cat gitCommit.txt
      - |
        GIT_TAG=$(cat gitCommit.txt)
        export IMAGE_TAG="v1.0.0-${CODEBUILD_BUILD_ID}-${GIT_TAG}"
        export ECR_REPO_LOWER=$(echo $ECR_REPO | tr '[:upper:]' '[:lower:]')
        export APP_IMAGE="${ECR_REPO_LOWER}:app-${IMAGE_TAG//[:]/-}"
      - echo "Logging into ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO
    finally:
      - echo "Pre-build phase complete."

  build:
    commands:
      - python -m pytest --junitxml results.xml polybot/test
      - echo "Building Docker image..."
      - cd polybot
      - docker build -t $APP_IMAGE_NAME:latest .
      - docker tag $APP_IMAGE_NAME:latest $APP_IMAGE
      - docker push $APP_IMAGE
      - echo "[{\"name\":\"app-container\",\"imageUri\":\"$APP_IMAGE\"}]" > imagedefinitions.json
      - mv imagedefinitions.json ../
    finally:
      - echo "Build phase complete."

artifacts:
  files:
    - imagedefinitions.json
