apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
   name: aws-secrets-provider
spec:
  provider: aws
  parameters:
    region: us-east-2
    failoverRegion: us-west-2
    pathTranslation: "none"
    objects: