apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ronn4-jenkins
  name: jenkins-deployment-manager
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]


